version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "8988:8181"
            - "8981:8182"
            - "8281:8180"
        volumes:
            - ./:/var/www
            - /var/www/html/NTF:/var/www/NTF
            - /var/www/html/NTF_1:/var/www/NTF_1
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mariadb:10.4
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-curupira}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
            MYSQL_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
            MYSQL_USER: ${DB_USERNAME:-curupira}
        volumes:
            - ./.docker/mariadb/dbdata:/var/lib/mysql
            - ./BackupBDCurupira-20240621-123001.sql:/docker-entrypoint-initdb.d/BackupBDCurupira-20240621-123001.sql
        ports:
            - "3388:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME:-curupira}
            PMA_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
        volumes:
            - ./docker/phpmyadmin:/etc/phpmyadmin # Volume mapeado da sua máquina para o container
        networks:
            - laravel

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
